### ISSUE TITLE
Issue with Hough_voting_cuda

### ISSUE THREAD

**Issue by RamyaRaghuraman** [chrisdxie/uois#1]
Hi @chrisdxie ,

Nice work on the paper!

Could you please explain the process for installing the hough_voting_cuda more clearly? I still get "ModuleNotFoundError: No module named 'hough_voting_cuda'"

**Comment by chrisdxie** [comment]
Hi @RamyaRaghuraman, 

Did you run `python setup.py install` while in the `uois` conda environment is activated?

**Comment by RamyaRaghuraman** [comment]
yes I did. I actually end up with this error
"C:\Users\RAR7ABT\AppData\Local\conda\conda\envs\test\lib\site-packages\torch\lib\include\torch\csrc\api\include\torch/torch.h(7): fatal error C1021: invalid preprocessor command 'warning'
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.22.27905\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2"

**Comment by chrisdxie** [comment]
Hmm, it seems that there was an error in the compilation. I have not tested the code on a Windows machine, only Linux. I'm afraid I cannot help you here. However, if you do manage to compile the hough voting layer, I believe it should work. Please let me know if you solve this issue.

**Comment by samuela** [comment]
@RamyaRaghuraman You may want to check out https://pytorch.org/docs/stable/notes/windows.html
