### ISSUE TITLE
Train DSN  on Tabletop Object Dataset 

### ISSUE THREAD

**Issue by aogonow** [chrisdxie/uois#10]
Hi, Firstly thank you for great work.

I have an issue when i try to train DSN on your tabletop object dataset following _train_DSN.ipynb_.
When I run cell with line : 

_dsn_trainer.train(num_epochs, dl)_

I recieve an **error** 

_FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "  ...  /venv/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "  ...  /venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "  ...  /venv/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "  ...   /uois/src/data_loader.py", line 183, in __getitem_\_
    scene_description = json.load(open(scene_description_filename))
FileNotFoundError: [Errno 2] No such file or directory: 
'  ...  /uois/tabletop_dataset_v5_public/training_set/scene_25580/scene_description.txt'_

I didn't change anything except _TOD_filepath_ and _tb_dir_.

I suppose it is simply due to a lack of _scene_description.txt_ in every sene. 

As I understand ''**scene_description** is  a Python dictionary describing scene''. Can you give example how it should look or how to generate/obtain it?

**Comment by chrisdxie** [comment]
Hi @aogonow, please re-download the dataset. The scene descriptions should be there.
