### ISSUE TITLE
RuntimeError: Sizes of tensors must match except in dimension 2. Got 53 and 52

### ISSUE THREAD

**Issue by maisylam99** [chrisdxie/uois#15]
Hello!

I am trying to run the model on my own images which have a dimension of 428x760. It seems that when images are not of the original sample image size (480x640) there is an issue with tensor sizes. I have a feeling this might be an issue with upsampling or encoding/decoding in the network. Any suggestions how I can work around this or correct in the code? 

Thanks!

![TensorIssue_1](https://user-images.githubusercontent.com/68020322/152584813-712de18a-8405-48ba-b7bc-cc9f14710aa8.png)
![TensorIssue_2](https://user-images.githubusercontent.com/68020322/152584823-a8e8f2a0-7cbb-4a12-a322-0625a1a5e104.PNG)

**Comment by chrisdxie** [comment]
Hi @maisylam99, I would suggest re-sizing your image to something that is a power of 2, that way the downsampling/upsampling agrees.
