### ISSUE TITLE
Unable to download dataset. 

### ISSUE THREAD

**Issue by Udeshcuddalore** [chrisdxie/uois#16]
Hello, I am trying to download Tabletop Object Dataset (TOD) from the link in the description. Initially it failed to download after downloading more than 50%, but now the google drive link is not accessible. 
Can someone help me with the alternate way to download the dataset? or is there any other version of the dataset? (As the original version is 35 GB size).
Thank you in advance!
I am pasting the google drive link 
https://drive.google.com/uc?export=download&id=157nWfb4pLbwAfOdMLls6q0lZQyqUCvLY

**Comment by chrisdxie** [comment]
Have you resolved this?

**Comment by Udeshcuddalore** [comment]
yes, I could download the dataset .Thank you.

**Comment by gaobaoding** [comment]
Hi @Udeshcuddalore,
I have the same issue after downloading around 50% using chrome. I appreciate it if you could explain how manage it :)
