### ISSUE TITLE
Trying reproduce Mark R-CNN method with input as Depth. 

### ISSUE THREAD

**Issue by Udeshcuddalore** [chrisdxie/uois#18]
Dear @chrisdxie ,
I am trying to reproduce one of the your evaluation methods. (Mask R-CNN method with input as Depth) . I have trained the network using the TOD_train  dataset. When I am using OCID and OSD as validation dataset. The results are very bad, the model seems to overfit on OCID validation dataset. I have looked into this repo. There is no code for how you produced the good results for OCID and OSD dataset [https://user-images.githubusercontent.com/23742278/148774850-1f5655f4-00d4-40e1-a2fd-1b89af7d318b.png](url) using Mask R-CNN with depth input. 
Kindly provide me the config details of how you trained Mask R-CNN with depth input. It would be really helpful.
Thank you @chrisdxie , if anyone else tried to evaluate on Mask R CNN please share the details for training and validation configs.

**Comment by chrisdxie** [comment]
You can find the config and codebase I forked here: https://github.com/chrisdxie/maskrcnn-benchmark/blob/master/configs/e2e_mask_rcnn_R_50_FPN_1x_TTOD_Depth.yaml
