### ISSUE TITLE
Error in installing hough voting layer (cudatoolkit = 9.1) 

### ISSUE THREAD

**Issue by ektas0330** [chrisdxie/uois#3]
Great work on the paper!

I am trying to use some of it for a related application. I have created a virtual environment using Anaconda and Pip as recommended. Details of the environment follow. (PyTorch didn't seem to have any binaries for CUDA 9.1, so I used the ones compiled with 9.0). `python setup.py install` gives multiple errors (see below). Any recommendations regarding what may have caused this error and how to fix it would be deeply appreciated.

### Environment details

Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 440.100
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.0.0
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.18.5           py37ha1c710e_0  
[conda] numpy-base                1.18.5           py37hde5b4d6_0  
[conda] pytorch                   1.0.0           py3.7_cuda9.0.176_cudnn7.4.1_1    pytorch

### Error

I get multiple errors (as included in the following file) when trying to install the Hough voting layer using `python setup.py install`

[error.txt](https://github.com/chrisdxie/uois/files/4927819/error.txt)

**Comment by chrisdxie** [comment]
Hi @ektas0330, my guess is that your CUDA runtime version and PyTorch CUDA version are slightly off. If that's the case, the compilation success is not guaranteed. Please try using a version of PyTorch that aligns with your CUDA runtime version.
