### ISSUE TITLE
Depth image normalization

### ISSUE THREAD

**Issue by aitorgutierrez** [chrisdxie/uois#5]
Hi!

How is the depth image normalization performed (xyz)?I check the original rgb and depth image, and the xyz (OCID_image_1.npy) image that you generated on the npy file. How is generated?
![depth-result_2018-08-21-14-24-14 (copy)](https://user-images.githubusercontent.com/35595129/98920523-7cc4c580-24d0-11eb-9e9f-603bb710bdcf.png)
![result_2018-08-21-14-24-14](https://user-images.githubusercontent.com/35595129/98920626-99f99400-24d0-11eb-87c6-71c2e625e37a.png)

**Comment by chrisdxie** [comment]
Hi @aitorgutierrez, the depth image is saved in millimeters. Please see the example notebook for how to load and visualize it.
