### ISSUE TITLE
Reproducibility on new dataset

### ISSUE THREAD

**Issue by nicolaihaeni** [chrisdxie/uois#6]
Hi 

I am trying to use your network out of the box on a new dataset. I am using your example to get ordered point clouds from the depth images (in mm). However the output for my images is all black. Any pointers why this might happen? I have attached an example output image for your reference.

![Figure_1](https://user-images.githubusercontent.com/15612666/115086758-7e0c7b00-9ed2-11eb-9e3d-92f9fb28d6d2.png)

Thanks

**Comment by chrisdxie** [comment]
Hmm, can you double check that the point cloud looks correct? Also, the point cloud does require that y decreases as the pixel increases, so you may have to flip the y coordinates of the point cloud.

**Comment by BHWWS** [comment]
Excuse me. How did you solve this problem? I meet the same one when trying to apply the model in our own dataset.
