### ISSUE TITLE
Using it on new data set.

### ISSUE THREAD

**Issue by mjm522** [chrisdxie/uois#7]
I tried using the network on 4 new images collected from an Intel Realsense. The output of the model is no where close to accurate. Should the model be retrained again with new data set. Following is the result I got.

![image](https://user-images.githubusercontent.com/15670626/122049586-81d95280-cdda-11eb-90df-378fa4500abb.png)

another:

![image](https://user-images.githubusercontent.com/15670626/122049749-acc3a680-cdda-11eb-8bd3-0c5e7a200cd1.png)

Any helpful suggestions on what direction I should move to make it work will be really helpful.

**Comment by mjm522** [comment]
I got better results when looking at an angle, like in the way data was collected at the scene. 

![image](https://user-images.githubusercontent.com/15670626/122054809-f06cdf00-cddf-11eb-82dc-4ff875820f00.png)

![image](https://user-images.githubusercontent.com/15670626/122054845-f6fb5680-cddf-11eb-928c-e813572c662b.png)

![image](https://user-images.githubusercontent.com/15670626/122054874-fcf13780-cddf-11eb-9aec-94aa4dc4ebb3.png)

**Comment by BHWWS** [comment]
How to pre-process the depth image obtained from Intel Realsense to match the data type used in the 
example_images ? I get much confused.

**Comment by chrisdxie** [comment]
Yes, it's ideal to collect data in a similar manner as the synthetic data is collected (mentioned in the paper). If I remember correctly, it's something like .5m - 1.2m above the table/planar surface, and at the edge of the table. 

Are your images flipped in the y-direction? We don't expect that, and I think you will get better results if you fix that.

**Comment by chrisdxie** [comment]
@BHWWS, to pre-process the depth image, just make sure the values are in meters, and that the y channel (of the XYZ point cloud image) is such that the values decrease as the pixel increases (y gets smaller as you travel down from pixel 0 to pixel H-1). 

Let me know if that helps.

**Comment by yellow07200** [comment]
@chrisdxie I'd like to test my model on OCID and OSD datasets, but how to preprocess the datasets as examples you provide? I see in data_loader.py, the focal length is required. If you also generate npy in this way, can you please provide the focal length you used? Many thanks!
