### ISSUE TITLE
Scene description files 

### ISSUE THREAD

**Issue by malsaidi93** [chrisdxie/uois#8]
Hi, I am trying to use your model uois3D on a new dataset. 
I'm facing a problem with the (process_label_3D) method as I don't have scene description.txt files. I downloaded the TOD dataset from the provided link, and still, I didn't see any scene description text files. 
Can you provide a sample of scene description files? Is it possible to use the model in 3D if these files weren't provided? 

Amazing work by the way!

**Comment by chrisdxie** [comment]
Hi @malsaidi93,

Thanks for pointing out this issue. I completely forgot to add the scene description files. I will add those in and re-release the data soon, likely in the next few days.

**Comment by malsaidi93** [comment]
> Hi @malsaidi93,
> 
> Thanks for pointing out this issue. I completely forgot to add the scene description files. I will add those in and re-release the data soon, likely in the next few days.

Hi @chrisdxie , 
Thank you for taking the time to look at this. I'm training on uois2D to bypass this issue but I'm interested in uois3D model more. Can you add a description of scene description files, how it's used and what it should contain? I plan on training the model on S3DIS dataset, any recommendations? Is there a way to avoid using this files while reasoning in 3D? 
Your feedback would be much appreciated!

**Comment by chrisdxie** [comment]
Hi @malsaidi93,

I have updated the dataset link. If you download it now, you should be able to find the scene descriptions and what they contain. I hope that helps!
