### ISSUE TITLE
How to pre-process the depth image obtained from Intel Realsense to match the data type used in the

### ISSUE THREAD

**Issue by BHWWS** [chrisdxie/uois#9]
How to pre-process the depth image obtained from Intel Realsense to match the data type used in the 
example_images ? I get much confused.

_Originally posted by @BHWWS in https://github.com/chrisdxie/uois/issues/7#issuecomment-894583657_

**Comment by chrisdxie** [comment]
See the my answer [here](https://github.com/chrisdxie/uois/issues/7).

**Comment by minorplanet0313** [comment]
Have you solved the problem now?
